name: 02-workflow-events

on:
    # pull_request:
    workflow_dispatch:

jobs:
    buid:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger event
              run: echo "The event that triggered this workflow was ${{ github.event_name}}"        