name: 04-Using-Actions

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run: # when we use defaults run, it will be applied to all the steps
                working-directory: 04-using-actions/react-app
        steps:
            - uses: actions/checkout@v4
              name: Checkout the repository

            - name: Printing folders
              run: ls -l # it will print the folders in the react-app directory and not the root directory

            - name: Set up node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'

            - name: Install dependencies
              run: npm ci
            #   working-directory: 04-using-actions/react-app

            - name: Test
              run: npm run test
            #   working-directory: 04-using-actions/react-app
