name: 08-variables

on:
    push:
    workflow_dispatch:

env:
    WORKFLOW_VAR: "I'M A WORKFLOW VARIABLE"
    OVERWRITTEN: "I'LL BE OVERWRITTEN"

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I'M A JOB VARIABLE"
            OVERWRITTEN: "I'LL BE OVERWRITTEN AT JOB LEVEL"
        steps:
            - name: Print ENV variables
              env:
                STEP_VAR: "I'M A STEP VARIABLE"
                step_var_2: "I'M A STEP VARIABLE 2"
              run: |
                echo "Step env var: $STEP_VAR"
                echo "Step env var 2: $step_var_2"
                echo "Job env var: $JOB_VAR"
                echo "Workflow env var: $WORKFLOW_VAR"
                echo "Overwritten: $OVERWRITTEN"
            - name: Overwrite job env var
              env:
                OVERWRITTEN: "I've been overwritten at step level"
              run: |
                echo "Step env var: $OVERWRITTEN"
