name: 11-working-with-inputs

on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: 'Skip deployment and only print build output' 
                # required: true
                type: boolean
                default: false
            target-env:
                type: environment
                required: true
                description: 'Target environment for deployment'
            tag:
                type: choice
                description: 'Choose a tag for deployment'
                options:
                    - v1
                    - v2
                    - v3
                default: v3

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building from tag ${{ inputs.tag }}"
    deploy-job:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}
        if: ${{ success() }} && ${{ !inputs.dry-run }}
        env:
            REGION: ${{ inputs.target-env.DEV_REGION }}
        steps:
            - name: Deploy
              run: |
                echo "Deploying to AWS Region ${{ env.REGION }}"