name: 12-outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo "GITHUB_OUTPUT_PATH=$GITHUB_OUTPUT"
            - name: Build
              id: build
              run: echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
        outputs:
            output-status: ${{ steps.build.outputs.status }}
    deploy-job:
        runs-on: ubuntu-latest
        needs: build-job
        if: ${{ needs.build-job.outputs.output-status == 'success' }} && ${{ success() }}
        steps:
            - name: Deploy
              run: echo "Deploying"
        