name: 12-outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo "GITHUB_OUTPUT_PATH=$GITHUB_OUTPUT"
            # both the steps don't share the same Github output file.
                # they are different.
            - name: Build
              id: build
              run: |
                echo "$GITHUB_OUTPUT_PATH=$GITHUB_OUTPUT"
                echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
                echo "output_1=This is output 1" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
        outputs:
            output-build-status: ${{ steps.build.outputs.status }}
            output_1-status: ${{ steps.build.outputs.output_1 }}
    deploy-job:
        runs-on: ubuntu-latest
        needs: build-job
        if: ${{ needs.build-job.outputs.output-build-status == 'success' }}
        steps:
            - name: Deploy
              run: echo "Deploying"
            - name: Print output_1
              run: echo "output_1=${{ needs.build-job.outputs.output_1-status }}"
